/* eslint-disable quotes */
/* eslint-disable prettier/prettier */
export default {
  translation: {
  "usernameOrEmail": "اسم المستخدم / البريد الإلكتروني",
  "name": "اسم",
  "email": "بريد إلكتروني",
  "password": "كلمة المرور",
  "send": "يرسل",
  "save": "يحفظ",
  "login": "تسجيل الدخول",
  "logout": "تسجيل خروج",
  "products": "منتجات",
  "productType": "نوع المنتج",
  "simple": "بسيط",
  "variable": "عامل",
  "editProduct": "تحرير المنتج",
  "addNewProduct": "اضافة منتج جديد",
  "productName": "اسم المنتج",
  "regular_price": "سعر عادي",
  "price": "سعر",
  "sale_price": "سعر البيع",
  "short_description": "وصف قصير",
  "productDescription": "وصف كامل",
  "inventory": "جرد",
  "sku": "SKU",
  "manageStock": "إدارة المخزون",
  "stock_quantity": "كمية المخزون",
  "stockStatus": "حالة الرصيد، وضع مخزون",
  "shipping": "شحن",
  "weight": "الوزن (كجم)",
  "diemensions": "الأبعاد",
  "length": "طول",
  "width": "عرض",
  "height": "ارتفاع",
  "saveProduct": "يحفظ",
  "seo": "سيو",
  "seoTitle": "عنوان",
  "seoDes": "وصف",
  "inStock": "في الأوراق المالية",
  "outOfStock": "إنتهى من المخزن",
  "addImage": "إضافة صورة",
  "confirmProductDeleteMessage": "هل أنت متأكد من حذف المنتج؟",
  "deleteConfirm": "يمسح",
  "cancelConfirm": "يلغي",
  "orders": "طلبات",
  "total": "المجموع",
  "voltComision": "لجنة فولت",
  "createdDate": "أنشئت في",
  "nowYouCanFindMe": "الآن يمكنك أن تجدني على Volt للتسوق عبر الإنترنت انقر فوق الرابط ",
  "theme": "سمة",
  "themes": "ثيمات",
  "defaultTheme": "السمة الافتراضية",
  "darkTheme": "مظهر داكن",
  "lightTheme": "مظهر خفيف",
  "contactUs": "اتصل بنا",
  "shareApp": "شارك التطبيق",
  "beAVendorWithVolt": "كن بائعًا مع Volt للتسوق عبر الإنترنت واجعل متجرك عبر الإنترنت للجميع.",
  "defaultLang": "اللغة الافتراضية",
  },
};
