/* eslint-disable quotes */
/* eslint-disable prettier/prettier */
export default {
  translation: {
    "usernameOrEmail": "Username / Email",
    "name": "Name",
    "email": "Email",
    "password": "Password",
    "send": "Send",
    "save": "Save",
    "login": "Sign in",
    "logout": "Logout",
    //  product form
    "products": "Products",
    "productType": "Product Type",
    "simple": "Simple",
    "variable": "Variable",
    "editProduct": "Edit Product",
    "addNewProduct": "Add New Product",
    "productName": "Product Name",
    "regular_price": "Regular Price",
    "price": "Price",
    "sale_price": "Sale Price",
    "short_description": "Short Description",
    "productDescription": "Full Description",
    "inventory": "Inventory",
    "sku": "Sku",
    "manageStock": "Manage Stock",
    "stock_quantity": "Stock Quantity",
    "stockStatus": "Stock Status",
    "shipping": "Shipping",
    "weight": "Weight (KG)",
    "diemensions": "Diemensions",
    "length": "Length",
    "width": "Width",
    "height": "Height",
    "saveProduct": "Save",
    "seo": "Seo",
    "seoTitle": "Title",
    "seoDes": "Description",
    "inStock": "In Stock",
    "outOfStock": "Out Of Stock",
    "addImage" : "Add Image",
    "confirmProductDeleteMessage": "Are you sure to delete product?",
    "deleteConfirm": "Delete",
    "cancelConfirm": "Cancel",
    // Orders
    "orders": "Orders",
    "total": "Total",
    "voltComision": "Volt Commision",
    "createdDate": "Created At",
    // menu
    "nowYouCanFindMe": "Now you can find me on Volt online shopping click the link ",
    "theme": "Theme",
    "themes": "Themes",
    "defaultTheme": "Default Theme",
    "darkTheme": "Dark Theme",
    "lightTheme": "Light Theme",
    "contactUs": "Contact Us",
    "shareApp": "Share App",
    "beAVendorWithVolt":
      "Be a vendor with Volt online shopping and make your store online for all.",
    "defaultLang": "Default Language",
  },
};
